name: Real-Time Azure Log Simulation

on:
  push:                        # Trigger saat ada push ke branch 'main'
    branches:
      - main
  schedule:
    - cron: "*/1 * * * *"  # Jalankan setiap 1 menit
  workflow_dispatch:        # Memungkinkan pemicu manual

jobs:
  real-time-logger:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          persist-credentials: true

      - name: Setup Git
        run: |
          git config --global user.name "herwinz"
          git config --global user.email "berlianherwindra@gmail.com"

      - name: Update Log File (60 Updates in 1 Minute)
        run: |
          for i in {1..60}; do
            echo "Running log update $i at $(date -u +'%Y-%m-%dT%H:%M:%S UTC')"
            chmod +x scripts/auto_log_update.sh
            ./scripts/auto_log_update.sh
            sleep 1
          done

      - name: Commit and Push Changes
        run: |
          git add logs/azure_monitor_log.json
          git commit -m "Automated Log Update: $(date -u)"
          git push origin main