name: Real-Time Azure Log Simulation

on:
  push:
  schedule:
    - cron: "*/1 * * * *"  # Update setiap 1 menit
  workflow_dispatch:        # Memungkinkan pemicu manual

jobs:
  real-time-logger:
    runs-on: ubuntu-latest

    permissions:            # Menambahkan izin write
      contents: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          persist-credentials: true  # Gunakan token default GitHub Actions

      - name: Setup Git
        run: |
          git config --global user.name "herwinz"
          git config --global user.email "berlianherwindra@gmail.com"

      - name: Run Real-Time Log Update
        run: |
          chmod +x scripts/auto_log_update.sh
          ./scripts/auto_log_update.sh