name: Real-Time Azure Log Simulation

on:
  push:                        # Trigger saat ada push ke branch 'main'
    branches:
      - main
  schedule:                    # Trigger otomatis setiap 1 menit
    - cron: "*/1 * * * *"
  workflow_dispatch:           # Trigger manual dari GitHub Actions UI

jobs:
  real-time-logger:
    runs-on: ubuntu-latest

    permissions:
      contents: write          # Izinkan write ke repository

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          persist-credentials: true  # Gunakan GITHUB_TOKEN default

      - name: Setup Git
        run: |
          git config --global user.name "herwinz"
          git config --global user.email "berlianherwindra@gmail.com"

      - name: Update Log File
        run: |
          git pull origin main
          chmod +x scripts/auto_log_update.sh
          ./scripts/auto_log_update.sh

      - name: Commit and Push Changes
        run: |
          git add logs/azure_monitor_log.json
          git commit -m "Automated Log Update: $(date -u +'%Y-%m-%d %H:%M:%S UTC')"
          git push origin main