name: Real-Time Azure Log Simulation

on:
  workflow_dispatch:        # Bisa dijalankan manual dari GitHub Actions UI
  push:                     # Trigger saat ada push ke branch 'main'
    branches:
      - main

jobs:
  real-time-logger:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          persist-credentials: true  # Gunakan GITHUB_TOKEN bawaan

      - name: Setup Git
        run: |
          git config --global user.name "herwinz"
          git config --global user.email "berlianherwindra@gmail.com"

      - name: Long-Running Log Update
        run: |
          # Loop tanpa henti
          while true; do
            echo "Starting 60-second log generation at $(date -u)"
            # Loop 60 detik untuk update log
            for i in {1..60}; do
              echo "Log update $i at $(date -u +'%Y-%m-%dT%H:%M:%S UTC')"
              chmod +x scripts/auto_log_update.sh
              ./scripts/auto_log_update.sh
              sleep 1  # Tunggu 1 detik
            done

            # Commit dan push setelah 60 detik selesai
            echo "Committing and pushing changes at $(date -u)"
            git add logs/azure_monitor_log.json
            git commit -m "Automated Log Update: $(date -u +'%Y-%m-%dT%H:%M:%S UTC')"
            git push origin main || echo "No changes to push"

            # Log status
            echo "60-second update cycle completed. Starting next cycle..."
          done